spring:
  profiles:
    active: local

eureka:
  dashboard:
    path: /eureka-web-ui
  server:
    enable-self-preservation: false
  client:
    healthcheck:
      enabled: false
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: local

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true



---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



---
spring:
  profiles: rancher-peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8760/eureka/

---
spring:
  profiles: rancher-peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8760/eureka/

